### ISSUE TITLE
Перечитай Homework 1-15

### ISSUE THREAD

**Issue by KokTis** [nbolatov/unsta#11]
Этим мы будем уверены, что твои -5 баллов не всплывут.
И последние HW будут имплементированы ПОЛНОСТЬЮ.

**Comment by nbolatov** [comment]
Айтуға оңай...

**Comment by nbolatov** [comment]
😅

**Comment by nbolatov** [comment]
Added share buttons

**Comment by nbolatov** [comment]
Added carousel

**Comment by nbolatov** [comment]
Я вспомнил насчет -5. Нужно было Карусель сделать, БД создать, сессии хранить, аналитикс подправить, meta таги подправить. Все это сделано.
